---
- hosts: agent
  connection: local
  gather_facts: no


  tasks:
    - name: Launch gcp instance {{item}}
      gce:
        instance_names: "{{instance_names}}"
        zone: us-central1-a
        machine_type: n1-standard-1
        image: ubuntu-1604
        state: present
        service_account_email: "{{ gce }}"
        credentials_file: "creds.json"
        project_id: "{{project_id}}"
      register: gce

    - name: install git
      apt: name=git state=latest update_cache=yes

#    - name: Save host data
#      add_host:
#        hostname: "{{ item.public_ip }}"
#        groupname: gce_instances_ips
#      with_items: "{{ gce.instance_data }}"
#      become: True
#
#    - name: Clone project to be run {{item}}
#      git:
#        repo: https://github.com/Nessaek/carriequotes.git
#        dest: gce_instances_ips
