---
- hosts: agent
  connection: local
  gather_facts: no

  tasks:
    - name: Launch gcp instance
      gce:
        instance_names: "{{instance_names}}"
        zone: us-central1-a
        machine_type: n1-standard-1
        image: ubuntu-1604
        state: present
        service_account_email: "{{ gce }}"
        credentials_file: "creds.json"
        project_id: "{{project_id}}"

#    - name: Tear down gcp instance
#      gce:
#        service_account_email: "{{ service_account_email }}"
#        credentials_file: "{{ credentials_file }}"
#        project_id: "{{ project_id }}"
#        instance_names: "{{ gce.instance_names }}"
#        zone: us-central1-a
#        state: absent




#    - name: Clone project to be run
#      git:
#        repo: https://github.com/Nessaek/carriequotes.git
#        dest: ~/
#      become: no


